import{chromium}from'playwright';import{writeFileSync,readFileSync}from'node:fs';import{resolve,dirname}from'node:path';import{createHash}from'node:crypto';
const here=dirname(import.meta.filename),root=process.env.SVG_APP_ROOT||resolve(here,'..'),browser=await chromium.launch({headless:true});
try{const page=await browser.newPage({viewport:{width:1180,height:850}});page.setDefaultTimeout(180000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const start=performance.now();await page.goto('http://127.0.0.1:8088');await page.waitForFunction(()=>document.querySelector('#status').textContent==='Ready');
 await page.locator('#file').setInputFiles(resolve(root,'fixtures/colors-resources.svg'));await page.waitForFunction(()=>document.querySelector('#source').value.includes('PAPAYAWHIP'));
 const before=await page.locator('#source').inputValue(),box=await page.locator('canvas').boundingBox();
 const pixel=()=>page.locator('canvas').evaluate(c=>Array.from(c.getContext('2d').getImageData(200,32,1,1).data).slice(0,3));const original=await pixel();
 await page.mouse.click(box.x+200*box.width/256,box.y+32*box.height/256);await page.locator('#property').selectOption('fill');await page.locator('#value').fill('hwb(120 0% 0% / 50%)');await page.locator('#set').click();await page.waitForFunction(()=>document.querySelector('#source').value.includes('fill:hwb(120 0% 0% / 50%)'));if(String(await pixel())!=='128,255,128')throw Error('Functional alpha color was not rendered in Bend');
 const colored=await page.locator('#source').inputValue();await page.locator('#property').selectOption('fill-opacity');await page.locator('#value').fill('50%');await page.locator('#set').click();await page.waitForFunction(()=>document.querySelector('#source').value.includes('fill:hwb(120 0% 0% / 50%);fill-opacity:50%'));const combined=await pixel();if(String(combined)!=='191,255,191')throw Error('Percentage opacity did not combine with alpha: '+combined+'; '+await page.locator('#source').inputValue());
 await page.locator('#undo').click();await page.waitForFunction(s=>document.querySelector('#source').value===s,colored);if(String(await pixel())!=='128,255,128')throw Error('Opacity undo differs');await page.locator('#undo').click();await page.waitForFunction(s=>document.querySelector('#source').value===s,before);if(String(await pixel())!==String(original))throw Error('Color undo differs');
 await page.locator('#property').selectOption('fill');await page.locator('#value').fill('REBECCAPURPLE');await page.locator('#set').click();await page.waitForFunction(()=>document.querySelector('#source').value.includes('fill:REBECCAPURPLE'));if(String(await pixel())!=='102,51,153')throw Error('Case-insensitive named color failed');
 if(errors.length)throw Error(errors.join('\n'));await page.screenshot({path:resolve(here,'web-colors-editor.png'),fullPage:true});const sourceSHA256=Object.fromEntries(['svg.bend','state.bend','web.bend','web.html'].map(f=>[f,createHash('sha256').update(readFileSync(resolve(root,f))).digest('hex')]));writeFileSync(resolve(here,'browser-colors-report.json'),JSON.stringify({passed:true,serverBackend:'native',durationSeconds:(performance.now()-start)/1000,checks:['load functional gradient/mask/pattern colors','edit HWB plus alpha','combine percentage fill-opacity','exact source and color undo','uppercase named color','no browser errors'],sourceSHA256,before,colored},null,2)+'\n');console.log('Color browser flow passed');
}finally{await browser.close();}
