import{chromium}from'playwright';import{writeFileSync,readFileSync}from'node:fs';import{resolve,dirname}from'node:path';import{createHash}from'node:crypto';
const here=dirname(import.meta.filename),root=process.env.SVG_APP_ROOT||resolve(here,'..'),browser=await chromium.launch({headless:true});
try{const page=await browser.newPage({viewport:{width:1180,height:850}});page.setDefaultTimeout(240000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const start=performance.now();await page.goto('http://127.0.0.1:8088');await page.waitForFunction(()=>document.querySelector('#status').textContent==='Ready');
 await page.locator('#file').setInputFiles(resolve(root,'fixtures/images-basic.svg'));await page.waitForFunction(()=>document.querySelector('#source').value.includes('data:image/png;base64,'));const before=await page.locator('#source').inputValue(),box=await page.locator('canvas').boundingBox();const pixel=(x,y)=>page.locator('canvas').evaluate((c,[x,y])=>Array.from(c.getContext('2d').getImageData(x,y,1,1).data).slice(0,3),[x,y]);
 if(String(await pixel(32,32))!=='230,60,40'||String(await pixel(80,32))!=='40,60,220')throw Error('Initial PNG pixels differ');console.log('Embedded PNG loaded');
 await page.mouse.click(box.x+32*box.width/256,box.y+32*box.height/256);await page.locator('#property').selectOption('width');await page.locator('#value').fill('12');await page.locator('#set').click();await page.waitForFunction(()=>document.querySelector('#source').value.includes('width:12'));if(String(await pixel(80,32))!=='255,255,255')throw Error('Image width edit did not resize');await page.locator('#undo').click();await page.waitForFunction(s=>document.querySelector('#source').value===s,before);if(String(await pixel(80,32))!=='40,60,220')throw Error('Image resize undo differs');console.log('Image resize and undo passed');
 await page.locator('#property').selectOption('opacity');await page.locator('#value').fill('0.5');await page.locator('#set').click();await page.waitForFunction(()=>document.querySelector('#source').value.includes('opacity:0.5'));const translucent=await pixel(32,32);if(translucent.some((v,i)=>Math.abs(v-[243,158,148][i])>1))throw Error('Image opacity differs: '+translucent);await page.locator('#undo').click();await page.waitForFunction(s=>document.querySelector('#source').value===s,before);
 await page.mouse.move(box.x+32*box.width/256,box.y+32*box.height/256);await page.mouse.down();await page.mouse.move(box.x+48*box.width/256,box.y+48*box.height/256);await page.mouse.up();await page.waitForFunction(s=>document.querySelector('#source').value!==s,before);if(String(await pixel(48,48))!=='230,60,40')throw Error('Dragged PNG pixels differ');await page.locator('#undo').click();await page.waitForFunction(s=>document.querySelector('#source').value===s,before);if(String(await pixel(32,32))!=='230,60,40')throw Error('Image drag undo differs');
 console.log('Image opacity, drag, and undo passed'); const downloading=page.waitForEvent('download');await page.locator('#download').click();const download=await downloading;const saved=resolve(here,'image-editor-saved.svg');await download.saveAs(saved);if(readFileSync(saved,'utf8')!==before)throw Error('Saved SVG did not preserve the original data URI');
 if(errors.length)throw Error(errors.join('\n'));await page.screenshot({path:resolve(here,'web-images-editor.png'),fullPage:true});const sourceSHA256=Object.fromEntries(['svg.bend','state.bend','web.bend','web.html'].map(f=>[f,createHash('sha256').update(readFileSync(resolve(root,f))).digest('hex')]));writeFileSync(resolve(here,process.env.SVG_SERVER_BACKEND==='javascript'?'browser-images-js-report.json':'browser-images-report.json'),JSON.stringify({passed:true,serverBackend:process.env.SVG_SERVER_BACKEND||'native',durationSeconds:(performance.now()-start)/1000,checks:['load PNG decoded by Bend','resize image','image opacity','exact source and pixel undo','drag image and undo','save preserves embedded PNG data URI','no browser errors'],sourceSHA256},null,2)+'\n');console.log('Image browser flow passed');
}finally{await browser.close();}
