import{chromium}from'playwright';import{writeFileSync,readFileSync}from'node:fs';import{resolve,dirname}from'node:path';import{createHash}from'node:crypto';
const here=dirname(import.meta.filename),root=process.env.SVG_APP_ROOT||resolve(here,'..'),browser=await chromium.launch({headless:true});
try{const page=await browser.newPage({viewport:{width:1180,height:850}});page.setDefaultTimeout(240000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const start=performance.now();await page.goto('http://127.0.0.1:8088');await page.waitForFunction(()=>document.querySelector('#status').textContent==='Ready');
 await page.locator('#file').setInputFiles(resolve(root,'fixtures/filters-basic.svg'));await page.waitForFunction(()=>document.querySelector('#source').value.includes('feComponentTransfer'));
 const before=await page.locator('#source').inputValue(),box=await page.locator('canvas').boundingBox();const pixel=(x,y)=>page.locator('canvas').evaluate((c,[x,y])=>Array.from(c.getContext('2d').getImageData(x,y,1,1).data).slice(0,3),[x,y]);
 if(String(await pixel(12,12))!=='238,68,51'||String(await pixel(24,12))!=='238,68,51')throw Error('Offset filter did not render in Bend');console.log('Filter fixture loaded');
 await page.mouse.click(box.x+12*box.width/256,box.y+12*box.height/256);await page.locator('#property').selectOption('filter');await page.locator('#value').fill('url(#matrix)');await page.locator('#set').click();await page.waitForFunction(()=>document.querySelector('#source').value.includes('filter:url(#matrix)'));
 if(String(await pixel(12,12))!=='51,238,68'||String(await pixel(24,12))!=='255,255,255')throw Error('Filter replacement did not update matrix');console.log('Filter property changed');
 await page.locator('#undo').click();await page.waitForFunction(s=>document.querySelector('#source').value===s,before);if(String(await pixel(24,12))!=='238,68,51')throw Error('Filter undo did not restore pixels');
 await page.locator('#value').fill('none');await page.locator('#set').click();await page.waitForFunction(()=>document.querySelector('#source').value.includes('filter:none'));if(String(await pixel(24,12))!=='255,255,255'||String(await pixel(12,12))!=='238,68,51')throw Error('Filter removal failed');
 await page.locator('#undo').click();await page.waitForFunction(s=>document.querySelector('#source').value===s,before);
 await page.mouse.move(box.x+12*box.width/256,box.y+12*box.height/256);await page.mouse.down();await page.mouse.move(box.x+18*box.width/256,box.y+18*box.height/256);await page.mouse.up();await page.waitForFunction(s=>document.querySelector('#source').value!==s,before);if(String(await pixel(30,18))!=='238,68,51')throw Error('Dragging did not transform filtered output');
 await page.locator('#undo').click();await page.waitForFunction(s=>document.querySelector('#source').value===s,before);if(String(await pixel(24,12))!=='238,68,51')throw Error('Drag undo did not restore filter pixels');
 if(errors.length)throw Error(errors.join('\n'));await page.screenshot({path:resolve(here,'web-filters-editor.png'),fullPage:true});const sourceSHA256=Object.fromEntries(['svg.bend','state.bend','web.bend','web.html'].map(f=>[f,createHash('sha256').update(readFileSync(resolve(root,f))).digest('hex')]));writeFileSync(resolve(here,process.env.SVG_SERVER_BACKEND==='javascript'?'browser-filters-js-report.json':'browser-filters-report.json'),JSON.stringify({passed:true,serverBackend:process.env.SVG_SERVER_BACKEND||'native',durationSeconds:(performance.now()-start)/1000,checks:['load Bend-rendered filters','replace filter reference','remove filter','exact source and pixel undo','drag filtered geometry and undo','no browser errors'],sourceSHA256,before},null,2)+'\n');console.log('Filter browser flow passed');
}finally{await browser.close();}
