// Only display and inspect Bend-supplied pixel matrices; SVG references are offline.
import{chromium}from'playwright';import{readFileSync,writeFileSync}from'node:fs';import{resolve,dirname}from'node:path';import{createHash}from'node:crypto';
const here=dirname(import.meta.filename),root=process.env.SVG_APP_ROOT||resolve(here,'..'),browser=await chromium.launch({headless:true});
try{const page=await browser.newPage({viewport:{width:1180,height:850}});page.setDefaultTimeout(240000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const start=performance.now();await page.goto('http://127.0.0.1:8088');await page.waitForFunction(()=>document.querySelector('#status').textContent==='Ready');await page.locator('#file').setInputFiles(resolve(root,'fixtures/filters-blend-compositing.svg'));await page.waitForFunction(()=>document.querySelector('#source').value.includes('mode="soft-light"'));
const before=await page.locator('#source').inputValue(),pixels=()=>page.locator('canvas').evaluate(c=>Array.from(c.getContext('2d').getImageData(0,0,256,256).data)),original=await pixels(),box=await page.locator('canvas').boundingBox(),rgb=(data,x,y)=>data.slice((y*256+x)*4,(y*256+x)*4+3).join(),headless=readFileSync(resolve(here,'filters-blend-compositing.ppm'),'utf8').trim().split(/\s+/).slice(4).map(Number),expected=(x,y)=>headless.slice((y*64+x)*3,(y*64+x)*3+3).join();
for(const[x,y]of [[16,16],[48,16],[16,48],[48,48]])if(rgb(original,x,y)!==expected(x,y))throw Error('Web matrix differs from Bend headless blend at '+[x,y]);console.log('Blend center pixels match headless');if(rgb(original,16,16)===rgb(original,48,16))throw Error('New blend modes produce identical center colors');
await page.mouse.click(box.x+16.5*box.width/256,box.y+16.5*box.height/256);await page.locator('#property').selectOption('filter');await page.locator('#value').fill('url(#soft)');await page.locator('#set').click();await page.waitForFunction(()=>document.querySelector('#source').value.includes('filter:url(#soft)'));const changed=await pixels();if(rgb(changed,16,16)!==rgb(original,48,16))throw Error('Switching hue to soft-light failed');if(changed.slice(32*256*4).join()!==original.slice(32*256*4).join())throw Error('Changing selected filter changed other shapes');
await page.locator('#undo').click();await page.waitForFunction(s=>document.querySelector('#source').value===s,before);if((await pixels()).join()!==original.join())throw Error('Blend property undo changed pixels');
await page.mouse.move(box.x+16.5*box.width/256,box.y+16.5*box.height/256);await page.mouse.down();await page.mouse.move(box.x+24.5*box.width/256,box.y+24.5*box.height/256);await page.mouse.up();await page.waitForFunction(s=>document.querySelector('#source').value!==s,before);if((await pixels()).join()===original.join())throw Error('Filtered shape did not move');await page.locator('#undo').click();await page.waitForFunction(s=>document.querySelector('#source').value===s,before);if((await pixels()).join()!==original.join())throw Error('Blend drag undo differs');
console.log('Blend filter edit, drag and exact undo passed');const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Save SVG'}).click({timeout:5000});const download=await downloadPromise,saved=readFileSync(await download.path(),'utf8');if(saved!==before||!saved.includes('mode="hue"')||!saved.includes('mode="soft-light"'))throw Error('Save lost blend primitives');if(errors.length)throw Error(errors.join('\n'));await page.screenshot({path:resolve(here,'web-blends-editor.png'),fullPage:true});
const sourceSHA256=Object.fromEntries(['svg.bend','state.bend','web.bend','web.html','fonts/NotoSans-Regular.ttf','fonts/NotoSans-Bold.ttf','fonts/NotoSans-Italic.ttf','fonts/NotoSans-BoldItalic.ttf'].map(f=>[f,createHash('sha256').update(readFileSync(resolve(root,f))).digest('hex')]));writeFileSync(resolve(here,process.env.SVG_SERVER_BACKEND==='javascript'?'browser-blends-js-report.json':'browser-blends-report.json'),JSON.stringify({passed:true,binarySHA256:process.env.SVG_SERVER_BINARY_SHA256||null,serverBackend:process.env.SVG_SERVER_BACKEND||'native',durationSeconds:(performance.now()-start)/1000,checks:['Bend web pixels match headless blend centers','select hue-filtered shape','switch to soft-light','other shapes unchanged','exact source and full-matrix undo','drag filtered shape and undo','save retains authored blend primitives','no browser errors'],sourceSHA256,before},null,2)+'\n');console.log('Blend editor flow passed');}finally{await browser.close();}
