import{chromium}from'playwright';import{writeFileSync,readFileSync}from'node:fs';import{resolve,dirname}from'node:path';import{createHash}from'node:crypto';
const here=dirname(import.meta.filename),root=process.env.SVG_APP_ROOT||resolve(here,'..'),browser=await chromium.launch({headless:true});
try{const page=await browser.newPage({viewport:{width:1180,height:850}});page.setDefaultTimeout(180000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const start=performance.now();await page.goto('http://127.0.0.1:8088');await page.waitForFunction(()=>document.querySelector('#status').textContent==='Ready');
 await page.locator('#file').setInputFiles(resolve(root,'fixtures/markers-context.svg'));await page.waitForFunction(()=>document.querySelector('#source').value.includes('context-stroke'));
 console.log('Marker fixture loaded');
 const before=await page.locator('#source').inputValue(),box=await page.locator('canvas').boundingBox();
 const pixel=()=>page.locator('canvas').evaluate(c=>Array.from(c.getContext('2d').getImageData(219,40,1,1).data).slice(0,3));const original=await pixel();if(String(original)!=='204,68,51')throw Error('Initial context marker color: '+original);
 await page.mouse.click(box.x+219*box.width/256,box.y+40*box.height/256);await page.locator('#property').selectOption('stroke');await page.locator('#value').fill('lime');await page.locator('#set').click();await page.waitForFunction(()=>document.querySelector('#source').value.includes('stroke:lime'));if(String(await pixel())!=='0,255,0')throw Error('Marker click did not select its owning path');
 console.log('Marker owner selected and context paint edited');
 const colored=await page.locator('#source').inputValue();await page.locator('#property').selectOption('marker-end');await page.locator('#value').fill('none');await page.locator('#set').click();await page.waitForFunction(()=>document.querySelector('#source').value.includes('marker-end:none'));if(String(await pixel())!=='255,255,255')throw Error('Marker property edit did not remove endpoint');
 console.log('Endpoint marker removed');
 await page.locator('#undo').click();await page.waitForFunction(s=>document.querySelector('#source').value===s,colored);if(String(await pixel())!=='0,255,0')throw Error('Marker property undo differs');await page.locator('#undo').click();await page.waitForFunction(s=>document.querySelector('#source').value===s,before);if(String(await pixel())!==String(original))throw Error('Context color undo differs');
 console.log('Property and color undo restored source');
 await page.mouse.move(box.x+219*box.width/256,box.y+40*box.height/256);await page.mouse.down();await page.mouse.move(box.x+235*box.width/256,box.y+48*box.height/256);await page.mouse.up();await page.waitForFunction(s=>document.querySelector('#source').value!==s,before);await page.locator('#undo').click();await page.waitForFunction(s=>document.querySelector('#source').value===s,before);if(String(await pixel())!==String(original))throw Error('Marker drag undo differs');
 if(errors.length)throw Error(errors.join('\n'));await page.screenshot({path:resolve(here,'web-markers-editor.png'),fullPage:true});const sourceSHA256=Object.fromEntries(['svg.bend','state.bend','web.bend','web.html'].map(f=>[f,createHash('sha256').update(readFileSync(resolve(root,f))).digest('hex')]));writeFileSync(resolve(here,process.env.SVG_SERVER_BACKEND==='javascript'?'browser-markers-js-report.json':'browser-markers-report.json'),JSON.stringify({passed:true,serverBackend:process.env.SVG_SERVER_BACKEND||'native',durationSeconds:(performance.now()-start)/1000,checks:['load marker context paints','pick marker selects owning path','stroke edit updates context paint','edit marker-end','exact source and color undo','drag via marker and undo','no browser errors'],sourceSHA256,before,colored},null,2)+'\n');console.log('Marker browser flow passed');
}finally{await browser.close();}
