// Display the saved Bend matrices and reference errors; no renderer is invoked.
import{readFileSync,writeFileSync}from'node:fs';import{resolve,dirname}from'node:path';import{PNG}from'pngjs';
const here=dirname(import.meta.filename),report=JSON.parse(readFileSync(resolve(here,'summary.json'),'utf8'));
function pngMatrix(name){const words=readFileSync(resolve(here,name+'.ppm'),'utf8').trim().split(/\s+/);if(words[0]!=='P3'||words[3]!=='255')throw Error('Invalid PPM');const width=+words[1],height=+words[2],png=new PNG({width,height});if(words.length!==4+width*height*3)throw Error('Wrong pixel count');for(let i=0;i<width*height;i++){for(let c=0;c<3;c++)png.data[i*4+c]=+words[4+i*3+c];png.data[i*4+3]=255;}writeFileSync(resolve(here,name+'.png'),PNG.sync.write(png));return name+'.png';}
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const rows=report.results.toSorted((a,b)=>Number(a.passed)-Number(b.passed)||a.fixture.localeCompare(b.fixture));
const cards=rows.map(r=>{const name=r.fixture.slice(0,-4),actual=pngMatrix(name),diff=pngMatrix(name+(r.reference==='resvg'?'-diff':'-'+r.reference+'-diff')),reference=name+(r.reference==='resvg'?'-reference.png':'-'+r.reference+'.png');return `<article data-passed="${r.passed}"><h2>${esc(r.fixture)} <span class="${r.passed?'pass':'fail'}">${r.passed?'PASS':'FAIL'}</span></h2><p>${esc(r.features.join(', '))}</p><div class="images"><figure><img src="${actual}" alt="Bend output for ${esc(r.fixture)}"><figcaption>Bend</figcaption></figure><figure><img src="${reference}" alt="Reference output"><figcaption>${esc(r.reference)}</figcaption></figure><figure><img src="${diff}" alt="Amplified absolute pixel difference"><figcaption>Difference ×4</figcaption></figure></div><p class="metrics">MAE ${r.meanAbsoluteError.toFixed(3)} · RMSE ${r.rootMeanSquareError.toFixed(3)} · Max ${r.maxChannelError} · Pixels &gt;32: ${r.pixelsAbove32}</p></article>`;}).join('\n');
writeFileSync(resolve(here,'gallery.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bend SVG pixel comparisons</title><style>body{margin:0;background:#f7f7f3;color:#172b33;font:16px system-ui,sans-serif}main{max-width:1180px;margin:48px auto;padding:0 24px}h1{font-size:34px;letter-spacing:-1px}h2{font-size:18px}header p{max-width:850px;line-height:1.6}section{display:grid;grid-template-columns:repeat(auto-fit,minmax(470px,1fr));gap:20px;margin-top:28px}article{padding:20px;background:white;border:1px solid #ddd;border-radius:12px}article p{font-size:13px;line-height:1.5}.images{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}figure{margin:0;text-align:center}img{width:100%;image-rendering:pixelated;border:1px solid #ddd;box-sizing:border-box}figcaption{font-size:12px;margin-top:6px}.pass{color:#246b48}.fail{color:#a33527}h2 span{float:right;font-size:12px}.metrics{font-variant-numeric:tabular-nums}label{display:inline-flex;align-items:center;gap:8px}article[hidden]{display:none}@media(max-width:550px){section{grid-template-columns:1fr}main{padding:0 12px}article{padding:12px}}</style><main><header><h1>Bend SVG pixel comparisons</h1><p><strong>${rows.filter(r=>r.passed).length}/${rows.length} fixtures pass.</strong> These are saved 64×64 images on white, with 8×8 coverage sampling in Bend. Passing requires MAE ≤1/255, RMSE ≤5/255, and no more than 1% of pixels with any channel difference above32. Differences are amplified four times. Failing cases are shown first.</p><p>Each fixture uses the reference selected in <a href="coverage.json">coverage.json</a>; references are rendered at 8&times; and box-averaged (see <a href="reference-scale.mjs">reference-scale.mjs</a>); raw alternate results remain in <a href="report.json">resvg</a>, <a href="chromium-report.json">Chromium</a> and <a href="firefox-all-report.json">Firefox</a> reports, with the earlier 1&times; comparisons retained as <code>*-x1.json</code> and <code>*-x1.png</code>. <a href="native-all-report.json">C/JavaScript parity</a> is checked separately. This gallery does not imply complete SVG conformance.</p><label><input id="failures" type="checkbox">Show only failing fixtures</label></header><section>${cards}</section></main><script>document.querySelector('#failures').onchange=e=>{for(const card of document.querySelectorAll('article'))card.hidden=e.target.checked&&card.dataset.passed==='true';};</script></html>\n`);
console.log(`Saved gallery.html for ${rows.length} fixtures`);
